### ISSUE TITLE
add list and remove commands not working

### ISSUE THREAD

**Issue by haragon-s** [detjensrobert/TwitchHoisterBot#9]
after setting everything up, all i can use is help and live command, while the other ones don't even show up in the help embed.

**Comment by detjensrobert** [comment]
Do you have a moderator role configured and assigned to you? The admin commands are not available to non-moderators.

**Comment by detjensrobert** [comment]
(Whoops, didnt mean to close)

**Comment by haragon-s** [comment]
no worries, it does work now, thank you so much, but im facing this issue whenever i stream and the bot seems not to have permissions to manage my roles even tho i gave it all the perms i could

![image](https://user-images.githubusercontent.com/83401018/129405645-9c23c287-2c68-4f5d-a5bc-b8ed513477e9.png)

**Comment by detjensrobert** [comment]
The bot cannot add roles higher in the chain than its highest role. The hoist role that the bot adds needs to be below the bot's in order for it to manage it.

![](https://i.imgur.com/1JV0iMa.png)

**Comment by haragon-s** [comment]
much appreciated, keep up the great work man!!
